### ISSUE TITLE
[Request] Favicon & Bookmark's background color

### ISSUE THREAD

**Issue by Rifhifi** [lucaseverett/toolbar-dial-chrome#3]
Hello Lucas,

Is it possible to add favicons on the left of bookmarks titles?

Furthermore it's disturbing to have for example Youtube in blue and Twitch in green.
I would like to be able to change the color, or have the possibility to have a simple neutral color.
E.g. an anthracite grey bookmark with 50% of opacity and with favicon could be nice.

**Comment by lucaseverett** [comment]
@Rifhifi Thank you for the suggestion!

Yes, I plan to add the option to change the color of the dial or to add a custom thumbnail for the dial in a future update.

Regarding favicons next to the titles, at this time I don't plan to add those.

**Comment by lucaseverett** [comment]
@Rifhifi I've decided that rather than add the ability to change the color, I'm going to update it so that the dial colors match the official brand colors for popular websites. For example, YouTube would be red, Twitch would be purple, and Facebook would be blue. I'll do the same thing for other popular social networking sites.

Are there any other sites you would expect to show the standard brand color, rather than a random color like is happening currently? Please let me know if you have any requests and I'll make sure they're included with the next update.

**Comment by Rifhifi** [comment]
The "Top sites" as you made on demo-beta is a good start I think. French topsites are pretty different : https://www.alexa.com/topsites/countries/FR
Most of websites I use are north american, french, and belgian, but I don't think I'm representative of most users. 

I have just one question about localisation. How will react the extension with different subdomains and tld for international websites? (fr.wikipedia.org instead of en.wkipedia.org, google.be, amazon.de, etc...)

**Comment by lucaseverett** [comment]
I'll make sure that the localized versions of international websites are all covered. I'm using the following list to get started.

https://www.visualcapitalist.com/wp-content/uploads/2019/08/top-100-websites-ranking.html

**Comment by lucaseverett** [comment]
The update for Chrome has been submitted to Google and should be available soon.

Closed by d7c4880f3643408784b9e08844c4087da39ac574.
